import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
const errors = []; page.on('pageerror', e => errors.push(e.message));
const clickSquare = async s => { const cell = page.locator(`[data-square="${s}"]`); await cell.click({button: (await cell.getAttribute('aria-pressed')) === 'true' ? 'left' : 'right'}); await page.waitForTimeout(450); };
try {
  await page.goto('http://homelab:5173');
  await page.locator('.connection.online').waitFor();
  await page.locator('#new-game').click();
  await page.waitForFunction(() => document.querySelector('#hex').textContent === '0xFFFF00000000FFFF');
  await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
  await page.locator('#play').click();
  await clickSquare('e2'); await clickSquare('e5');
  assert.match(await page.locator('#status').textContent(), /Geçersiz/);
  assert.ok(await page.locator('.square.blink').count() > 0);
  await clickSquare('e5'); await clickSquare('e2');
  await clickSquare('e2'); await clickSquare('e4');
  assert.equal(await page.locator('#last-move').textContent(), 'e4');
  await clickSquare('d7'); await clickSquare('d5');
  await clickSquare('d5'); await clickSquare('e4');
  await page.getByRole('button', {name:'Select held piece from e4', exact:true}).click();
  await clickSquare('d5');
  assert.equal(await page.locator('#last-move').textContent(), 'exd5');
  assert.equal(await page.locator('[data-square="d5"] .piece.white').count(), 1);
  await page.locator('.setup-drawer summary').click();
  await page.locator('#fen').fill('r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1');
  await page.locator('#load-fen').click(); await page.locator('.setup-drawer summary').click(); await page.locator('#play').click();
  await clickSquare('e1'); await clickSquare('h1');
  assert.equal(await page.locator('.held-piece').count(), 2);
  assert.equal(await page.locator('[data-mobile-square="e1"] .piece').count(), 1);
  await clickSquare('g1'); await clickSquare('f1');
  assert.equal(await page.locator('#last-move').textContent(), 'O-O');
  assert.equal(await page.locator('[data-mobile-square="g1"] .piece').count(), 1);
  assert.equal(await page.locator('.held-piece').count(), 0);
  await page.locator('#new-game').click(); await page.locator('#ai-mode').click(); await page.locator('#play').click();
  await clickSquare('e2'); await clickSquare('e4');
  await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('Stockfish:'), { timeout: 30000 });
  const recommendation = await page.locator('#status').textContent();
  const [, from, to] = recommendation.match(/Stockfish: ([a-h][1-8]) → ([a-h][1-8])/);
  assert.equal(await page.locator('.square.led').count(), 2);
  await clickSquare(from); await clickSquare(to);
  assert.equal(await page.locator('#move-number').textContent(), '2 yarım hamle');
  await page.locator('#new-game').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile horizontal overflow');
  assert.equal(await page.locator('#mobile-board .square').count(), 64);
  assert.equal(await page.locator('#mobile-board button').count(), 0);
  assert.ok(await page.locator('.from-board').count() > 0);
  assert.ok(await page.locator('.from-mobile').count() > 0);
  assert.deepEqual(errors, []);
  const phone = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  await phone.goto('http://homelab:5173'); await phone.locator('.connection.online').waitFor();
  await phone.locator('[data-square="e2"]').tap();
  await phone.waitForTimeout(100);
  await phone.locator('#place-mode').tap(); await phone.locator('[data-square="e4"]').tap();
  await phone.waitForTimeout(100);
  assert.equal(await phone.locator('[data-square="e4"]').getAttribute('aria-pressed'),'true');
  await phone.locator('#new-game').tap(); await phone.close();
  console.log('PASS: invalid move recovery, capture, real Stockfish WASM → LEDs → physical reply, mobile layout, read-only client, protocol navigation; no page errors.');
} finally { await browser.close(); }
